# Generated by Django 3.1.2 on 2020-10-27 22:53

from django.db import migrations, models
import django.db.models.deletion
import meals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('calorie_level', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(choices=[(meals.models.IngredientUnit['GRAMS'], 'g'), (meals.models.IngredientUnit['TABLE_SPOON'], 'tbsp'), (meals.models.IngredientUnit['TEA_SPOON'], 'tsp'), (meals.models.IngredientUnit['SIZE'], 'size'), (meals.models.IngredientUnit['CLOVE'], 'clove'), (meals.models.IngredientUnit['HANDFUL'], 'handful')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(related_name='meals', through='meals.Ingredient', to='meals.Item')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.item'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
