# Generated by Django 3.1.2 on 2020-10-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20201027_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
