# Generated by Django 3.1.2 on 2020-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20201027_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('tbsp', 'Table spoon'), ('tsp', 'Tea spoon'), ('size', 'Size'), ('clove', 'Clove'), ('handful', 'Handful')], max_length=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
