# Generated by Django 3.1.2 on 2020-10-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_ingredient_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('tbsp', 'Table spoon'), ('tsp', 'Tea spoon'), ('size', 'Size'), ('clove', 'Clove'), ('handful', 'Handful'), ('slice', 'Slice')], max_length=10),
        ),
    ]
