# Generated by Django 3.1.2 on 2020-10-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_auto_20201028_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('tbsp', 'Table spoon'), ('tsp', 'Tea spoon'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('size', 'Size'), ('clove', 'Clove'), ('handful', 'Handful'), ('slice', 'Slice'), ('ml', 'Milliliter')], max_length=10),
        ),
    ]
