# Generated by Django 3.1.2 on 2020-10-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_daytimemeal_weeklyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytimemeal',
            name='calorie_level',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
            preserve_default=False,
        ),
    ]
